server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/signup?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: jaehongmin3627@gmail.com
    password: czsi iovu mxoe ayzo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30?
  jpa:
    hibernate:
      # ddl-auto: update # 기존 더미 데이터 삭제되지 않게
      ddl-auto: create # 매번 db 초기화하고 시작
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.hibernate.SQL: DEBUG