name: Deploy to EC2

# main 브랜치로 push 되었을때 해당 workflow 를 실행시켜라
on:
  push:
    branches:
      - main

jobs:
  Deploy:
    # jobs 실행 환경 필수적으로 명시해야함
    # ubuntu OS 에서 실행시키는 작업이다~
    runs-on: ubuntu-latest
    steps:
      - name: set variables by github secrets and deploy gradle-built jar on ec2
        uses: appleboy/ssh-action@v1.0.3
        with:

          # workflow 가 실행될때 Github Secrets 에 설정된 값을 참조해서 동적으로 스크립트를 완성시키고 실행시킴
          host: ${{ secrets.EC2_HOST }} # EC2 IP 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 사용자 이름
          key: ${{ secrets.EC2_PRIVATE_KEY }} # EC2 KEY

          script_stop: true

          script: |
    
            cd /home/ubuntu/signup
            git pull origin main
            
            chmod +x ./gradlew
            ./gradlew clean build
            
            sudo fuser -k -n tcp 8080 || true
            nohup java -Xms80m -Xmx120m -jar build/libs/*SNAPSHOT.jar --spring.profiles.active=prod > ./console.log 2>&1 &