name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Access EC2 via SSH for remote connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          # GITHUB-SETTINGS-SECRETS 에서
          # EC2 IP 주소
          host: ${{ secrets.EC2_HOST }}
          # EC2 사용자 이름
          username: ${{ secrets.EC2_USERNAME }}
          # EC2 KEY
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script_stop: true
          # 1. EC2에서 프로젝트 경로로 이동
          # 2. EC2에서 pull 실행
          # 3. build 해서 .jar 파일 다시 만들어주기
          # 4. 기존에 8080 포트로 올라간 것을 꺼주거나,
          # 서버가 안올라가 있을 경우에는 앞에꺼가 false 가 뜨므로 안올라가 있을떄는 무조건 true 되게 하기
          # 5. EC2에 GITHUB SECRETS에 올라가 있는 OPENAI_KEY를 환경변수로 등록하기
          # 6. 백그라운드로 돌리기 위해 nohup 쓰고 SNAPSHOT.jar 파일을 실행시키기
          # (로그를 콘솔창이 아니라 output.log 에 남겨줘) feat 표준출력

          # application.yml 환경변수 처리하려면 여기 script 에 추가 코드 작성
          script: |
            cd /home/ubuntu/SignUp
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &